--- #YAML:1.0
name:               Params-Lazy
version:            0.003
abstract:           Transparent lazy arguments for subroutines.
author:
    - Brian Fraser <fraserbn@gmail.com>
license:            Artistic_2_0
distribution_type:  module
configure_requires:
    Devel::CallChecker:   0
    ExtUtils::MakeMaker:  0
    IO::File:             0
build_requires:
    Test::More:  0.98
requires:
    Devel::CallChecker:  0
    perl:                5.008008
    strict:              0
    Test::More:          0.98
    warnings:            0
    XSLoader:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
