---
abstract: 'Transparent lazy arguments for subroutines.'
author:
  - 'Brian Fraser <fraserbn@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  Devel::CallChecker: 0
  ExtUtils::MakeMaker: 0
  IO::File: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Params-Lazy
no_index:
  directory:
    - t
    - inc
requires:
  Devel::CallChecker: 0
  XSLoader: 0
  perl: 5.008008
  strict: 0
  warnings: 0
version: 0.004
